version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - gocritic
    - gocyclo
    - dupl
    - goconst
    - misspell
    - noctx
    - gosec

  settings:
    gocyclo:
      min-complexity: 30

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - commentedOutCode
        - hugeParam
        - paramTypeCombine
        - dupImport
        - emptyStringTest
        - httpNoBody
        - equalFold

run:
  timeout: 5m

exclusions:
  # Paths to exclude from linting
  paths:
    - vendor
    - third_party

  rules:
    # Test files are less strict
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - errcheck
        - gosec
        - gocritic
