version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - gocritic
    - gocyclo
    - dupl
    - goconst
    - misspell
    - noctx
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - hugeParam

issues:
  exclude-rules:
    # Test files are less strict
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - errcheck
        - gosec

run:
  timeout: 5m
  exclude-dirs:
    - vendor
    - third_party
