/**
 * @file densecore_version.h
 * @brief DenseCore version information (auto-generated by CMake)
 *
 * DO NOT EDIT THIS FILE DIRECTLY - it is generated from version.h.in
 */

#ifndef DENSECORE_VERSION_H
#define DENSECORE_VERSION_H

// Version components
#define DENSECORE_VERSION_MAJOR 1
#define DENSECORE_VERSION_MINOR 0
#define DENSECORE_VERSION_PATCH 0

// Version as string "X.Y.Z"
#define DENSECORE_VERSION_STRING "1.0.0"

// Git commit hash (short)
#define DENSECORE_GIT_COMMIT "5781039"

// Build timestamp (ISO 8601 UTC)
#define DENSECORE_BUILD_TIMESTAMP "2025-12-25T03:29:26Z"

// Full version string with commit: "X.Y.Z (abc1234)"
#define DENSECORE_VERSION_FULL                                                 \
  "1.0.0 (5781039)"

// Numeric version for comparison: MAJOR * 10000 + MINOR * 100 + PATCH
#define DENSECORE_VERSION_NUMBER                                               \
  (DENSECORE_VERSION_MAJOR * 10000 + DENSECORE_VERSION_MINOR * 100 +           \
   DENSECORE_VERSION_PATCH)

#endif // DENSECORE_VERSION_H
